spring.application.name=ping-service
server.port=9091

management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.prometheus.enabled=true
management.metrics.tags.application=${spring.application.name}

# incident-service
services.service.url=http://incedent-service:8079/api/incident-service
services.service.healthEndpoint=/health

# incident-processor
services.processor.url=http://incident-processor-service:8086/api/incident-processor
services.processor.healthEndpoint=/health

# incident-producer-service
services.producerService.url=http://incedent-producer-service:8082/api/incident-producer-service
services.producerService.healthEndpoint=/health

# alert-service
services.alertService.url=http://localhost:8085/api/alert-service
services.alertService.healthEndpoint=/health

