spring.application.name=ping-service
server.port=9091

management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.prometheus.enabled=true
management.metrics.tags.application=${spring.application.name}

# incident-service
services.service.url=http://localhost:8079/api/incedent-service
services.service.healthEndpoint=/actuator/health

# incident-processor
services.processor.url=http://localhost:8086/api/incedent-processor
services.processor.healthEndpoint=/actuator/health

# incident-producer-service
services.producerService.url=http://localhost:8082/api/incedent-producer-service
services.producerService.healthEndpoint=/actuator/health

