spring.application.name=ping-service
server.port=9091

# incident-service
services.service.url=http://localhost:8079/api/incident-service
services.service.healthEndpoint=/health

# incident-processor
services.processor.url=http://localhost:8086/api/incedent-processor
services.processor.healthEndpoint=/actuator/health

# incident-producer-service
services.producerService.url=http://localhost:8082/api/incident-producer-service
services.producerService.healthEndpoint=/health
