services:
  ping-service:
    build: .
    container_name: ping-service
    ports:
      - "9091:9091"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      SPRING_KAFKA_SCHEMA_REGISTRY_URL: http://schema-registry:8081
    restart: on-failure
    networks:
      - app-network

networks:
  app-network:
    external: true
    name: app-network