global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'incedent-project-local'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - 'host.docker.internal:8079'
          - 'host.docker.internal:8082'
          - 'host.docker.internal:8086'
          - 'host.docker.internal:9091'
          - 'host.docker.internal:8085'
        labels:
          application: 'incident-project'
          environment: 'development'

  - job_name: 'incedent-project-docker'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - 'incedent-service:8079'
          - 'incedent-producer-service:8082'
          - 'incident-processor-service:8086'
          - 'ping-service:9091'
          - 'alert-service:8085'
        labels:
          application: 'incident-project'
          environment: 'docker'